package s1.m1;

/*Generated by MPS */

import common.interfaces.AbstractIPointerTarget;
import common.interfaces.IPointer;
import java.util.HashSet;
import java.util.Arrays;
import common.interfaces.IPointerTarget;
import s1.m2.a1_m2;
import s1.m2.b1_m2;
import s2.m1.a1_s2m1;
import s2.m1.b1_s2m1;

public class a2 extends AbstractIPointerTarget {

  private static final String[] canPointToMeMetaType = {"A"};

  private static final String[] canPointToMeClass = {"a1"};

  @Override
  public String metaType() {
    return "A";
  }

  @Override
  public String name() {
    return "a2";
  }

  @Override
  public boolean canPointToMe(IPointer inPointer) {
    String metaType = inPointer.target().metaType();
    String name = inPointer.target().name();
    HashSet<String> mtSet = new HashSet(Arrays.asList(canPointToMeMetaType));
    HashSet<String> clSet = new HashSet(Arrays.asList(canPointToMeClass));
    return mtSet.contains(metaType) && clSet.contains(name);
  }


  private IPointer pointerTo_a2_to_b1 = null;
  private IPointer pointerTo_a2_to_a1 = null;
  private IPointer pointerTo_a2_to_a1_m2 = null;
  private IPointer pointerTo_a2_to_b1_m2 = null;
  private IPointer pointerTo_a2_to_a1_s2m1 = null;
  private IPointer pointerTo_a2_to_b1_s2m1 = null;

  public void pointTo(final b1 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_a2_to_b1 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final a1 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_a2_to_a1 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final a1_m2 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_a2_to_a1_m2 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final b1_m2 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_a2_to_b1_m2 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final a1_s2m1 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_a2_to_a1_s2m1 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final b1_s2m1 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_a2_to_b1_s2m1 = ip;
    ip.target().pointsToMe(ip);
  }
}
