package s1.m1;

/*Generated by MPS */

import common.interfaces.AbstractIPointerTarget;
import common.interfaces.IPointer;
import java.util.HashSet;
import java.util.Arrays;
import common.interfaces.IPointerTarget;
import s1.m2.a1_m2;
import s1.m2.b1_m2;

public class b1 extends AbstractIPointerTarget {
  private static final String[] canPointToMeMetaType = {"A"};

  private static final String[] canPointToMeClass = {"a1", "a2"};

  @Override
  public String metaType() {
    return "B";
  }

  @Override
  public String name() {
    return "b1";
  }

  @Override
  public boolean canPointToMe(IPointer inPointer) {
    String metaType = inPointer.target().metaType();
    String name = inPointer.target().name();
    HashSet<String> mtSet = new HashSet(Arrays.asList(canPointToMeMetaType));
    HashSet<String> clSet = new HashSet(Arrays.asList(canPointToMeClass));
    return mtSet.contains(metaType) && clSet.contains(name);
  }


  private IPointer pointerTo_b1_to_b2 = null;
  private IPointer pointerTo_b1_to_a1_m2 = null;
  private IPointer pointerTo_b1_to_b1_m2 = null;

  public void pointTo(final b2 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_b1_to_b2 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final a1_m2 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_b1_to_a1_m2 = ip;
    ip.target().pointsToMe(ip);
  }
  public void pointTo(final b1_m2 target) {
    IPointer ip = new IPointer() {
      public IPointerTarget target() {
        return target;
      }
    };
    pointerTo_b1_to_b1_m2 = ip;
    ip.target().pointsToMe(ip);
  }
}
