package sample.lang2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptB = createDescriptorForB();
  /*package*/ final ConceptDescriptor myConceptB_Reference = createDescriptorForB_Reference();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptB, myConceptB_Reference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.B:
        return myConceptB;
      case LanguageConceptSwitch.B_Reference:
        return myConceptB_Reference;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForB() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("sample.lang2", "B", 0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL);
    b.class_(false, false, true);
    b.parent(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x2f9ba7da1a4d85eeL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3fb367ae-1b65-4273-9650-d1f0314333d4(sample.lang2.structure)/8216867906302305421");
    b.aggregate("b_PointsTo", 0x72082dd37174e4aeL).target(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e48eL).optional(true).ordered(true).multiple(true).origin("8216867906302305454").done();
    b.aggregate("pointedBy_a", 0x72082dd37174e4b1L).target(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e4b9L).optional(true).ordered(true).multiple(true).origin("8216867906302305457").done();
    b.aggregate("pointedBy_b", 0x72082dd37174e4c0L).target(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e4b9L).optional(true).ordered(true).multiple(true).origin("8216867906302305472").done();
    b.alias("b");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForB_Reference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("sample.lang2", "B_Reference", 0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e492L);
    b.class_(false, false, false);
    b.parent(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e49eL);
    b.origin("r:3fb367ae-1b65-4273-9650-d1f0314333d4(sample.lang2.structure)/8216867906302305426");
    b.associate("target", 0x72082dd37174e493L).target(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL).optional(false).origin("8216867906302305427").done();
    return b.create();
  }
}
