package sample.lang.common.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import sample.lang.common.behavior.ISmartRef__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class fix_pto_QuickFix extends QuickFix_Runtime {
  public fix_pto_QuickFix() {
    super(new SNodePointer("r:4dc348d4-7899-4de3-9960-a7da22d4aaec(sample.lang.common.typesystem)", "8216867906302647253"));
  }
  public void execute(SNode node) {
    SNode par = SNodeOperations.getParent(((SNode) fix_pto_QuickFix.this.getField("p")[0]));
    SNode target = ISmartRef__BehaviorDescriptor.target_id788btdLtKiq.invoke(SLinkOperations.getTarget(((SNode) fix_pto_QuickFix.this.getField("p")[0]), MetaAdapterFactory.getContainmentLink(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e48eL, 0x72082dd37174e48fL, "ref")));
    SNode pointedBy = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e4b9L, "sample.lang.common.structure.PointedBy"));
    SLinkOperations.setTarget(pointedBy, MetaAdapterFactory.getReferenceLink(0xc1700382310d4ee1L, 0x9c2a40abb0a5fca3L, 0x72082dd37174e4b9L, 0x72082dd3717533f9L, "inref"), ((SNode) fix_pto_QuickFix.this.getField("p")[0]));
    {
      final SNode apar = par;
      if (SNodeOperations.isInstanceOf(apar, MetaAdapterFactory.getConcept(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48cL, "sample.lang.structure.A"))) {
        {
          final SNode aTar = target;
          if (SNodeOperations.isInstanceOf(aTar, MetaAdapterFactory.getConcept(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48cL, "sample.lang.structure.A"))) {
            ListSequence.fromList(SLinkOperations.getChildren(aTar, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48cL, 0x72082dd37174e4cfL, "pointedBy_a"))).addElement(pointedBy);
          }
        }
        {
          final SNode bTar = target;
          if (SNodeOperations.isInstanceOf(bTar, MetaAdapterFactory.getConcept(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, "sample.lang2.structure.B"))) {
            ListSequence.fromList(SLinkOperations.getChildren(bTar, MetaAdapterFactory.getContainmentLink(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, 0x72082dd37174e4b1L, "pointedBy_a"))).addElement(pointedBy);
          }
        }
      }
    }
    {
      final SNode bpar = par;
      if (SNodeOperations.isInstanceOf(bpar, MetaAdapterFactory.getConcept(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, "sample.lang2.structure.B"))) {
        {
          final SNode aTar = target;
          if (SNodeOperations.isInstanceOf(aTar, MetaAdapterFactory.getConcept(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48cL, "sample.lang.structure.A"))) {
            ListSequence.fromList(SLinkOperations.getChildren(aTar, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48cL, 0x72082dd37174e4d0L, "pointedBy_b"))).addElement(pointedBy);
          }
        }
        {
          final SNode bTar = target;
          if (SNodeOperations.isInstanceOf(bTar, MetaAdapterFactory.getConcept(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, "sample.lang2.structure.B"))) {
            ListSequence.fromList(SLinkOperations.getChildren(bTar, MetaAdapterFactory.getContainmentLink(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, 0x72082dd37174e4c0L, "pointedBy_b"))).addElement(pointedBy);
          }
        }
      }
    }
  }
}
