package sample.lang.migration;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptBase;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SearchScope;
import jetbrains.mps.lang.smodel.query.runtime.CommandUtil;
import jetbrains.mps.lang.smodel.query.runtime.QueryExecutionContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import jetbrains.mps.lang.structure.plugin.RefactoringRuntime;
import jetbrains.mps.lang.migration.runtime.base.Problem;
import jetbrains.mps.internal.collections.runtime.ISequenceClosure;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.closures.runtime.YieldingIterator;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.lang.migration.runtime.base.DeprecatedConceptNotMigratedProblem;
import jetbrains.mps.lang.migration.runtime.base.DeprecatedConceptMemberNotMigratedProblem;
import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class MigrationScript_1 extends MigrationScriptBase {
  public String getCaption() {
    return "Move nodes refactoring";
  }
  @Override
  public boolean isRerunnable() {
    return true;
  }
  public SNode execute(final SModule m) {
    doExecute(m);
    return null;
  }
  public void doExecute(final SModule m) {
    {
      final SearchScope scope = CommandUtil.createScope(m);
      QueryExecutionContext context = new QueryExecutionContext() {
        public SearchScope getDefaultSearchScope() {
          return scope;
        }
      };
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SConceptOperations.isExactly(SNodeOperations.asSConcept(SNodeOperations.getConcept(it)), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e492L, "B_Reference")));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.replaceWithNewConcept(node, MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e492L, "B_Reference"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B"))) || MigrationScript_1.isMovedConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeContainmentLinkInstance(node, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4aeL, "b_PointsTo"), MetaAdapterFactory.getContainmentLink(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, 0x72082dd37174e4aeL, "b_PointsTo"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B"))) || MigrationScript_1.isMovedConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeContainmentLinkInstance(node, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4b1L, "pointedBy_a"), MetaAdapterFactory.getContainmentLink(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, 0x72082dd37174e4b1L, "pointedBy_a"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B"))) || MigrationScript_1.isMovedConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeContainmentLinkInstance(node, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4c0L, "pointedBy_b"), MetaAdapterFactory.getContainmentLink(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e48dL, 0x72082dd37174e4c0L, "pointedBy_b"));
        }
      });
      Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e492L, "B_Reference"))) || MigrationScript_1.isMovedConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e492L, "B_Reference"));
        }
      }).visitAll(new IVisitor<SNode>() {
        public void visit(SNode node) {
          RefactoringRuntime.changeReferenceLinkInstances(node, MetaAdapterFactory.getReferenceLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e492L, 0x72082dd37174e493L, "target"), MetaAdapterFactory.getReferenceLink(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, 0x72082dd37174e492L, 0x72082dd37174e493L, "target"));
        }
      });
    }
  }
  @Override
  public Iterable<Problem> check(SModule m) {
    {
      final SearchScope scope = CommandUtil.createScope(m);
      final QueryExecutionContext context = new QueryExecutionContext() {
        public SearchScope getDefaultSearchScope() {
          return scope;
        }
      };
      return Sequence.fromClosure(new ISequenceClosure<Problem>() {
        public Iterable<Problem> iterable() {
          return new Iterable<Problem>() {
            public Iterator<Problem> iterator() {
              return new YieldingIterator<Problem>() {
                private int __CP__ = 0;
                protected boolean moveToNext() {
__loop__:
                  do {
__switch__:
                    switch (this.__CP__) {
                      case -1:
                        assert false : "Internal error";
                        return false;
                      case 2:
                        this._2__yield_zc5nt1_a0a0c0a0e_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 3:
                        if (!(this._2__yield_zc5nt1_a0a0c0a0e_it.hasNext())) {
                          this.__CP__ = 5;
                          break;
                        }
                        this._2__yield_zc5nt1_a0a0c0a0e = this._2__yield_zc5nt1_a0a0c0a0e_it.next();
                        this.__CP__ = 4;
                        break;
                      case 5:
                        this._6__yield_zc5nt1_b0a0c0a0e_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e492L, "B_Reference"))) && !(SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e492L, "B_Reference"))));
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            Problem problem = new DeprecatedConceptNotMigratedProblem(it);
                            return problem;
                          }
                        })).iterator();
                      case 7:
                        if (!(this._6__yield_zc5nt1_b0a0c0a0e_it.hasNext())) {
                          this.__CP__ = 9;
                          break;
                        }
                        this._6__yield_zc5nt1_b0a0c0a0e = this._6__yield_zc5nt1_b0a0c0a0e_it.next();
                        this.__CP__ = 8;
                        break;
                      case 9:
                        this._10__yield_zc5nt1_c0a0c0a0e_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getChildren(MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4aeL, "b_PointsTo")).iterator().hasNext();
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedContainmentLink(it, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4aeL, "b_PointsTo"));
                          }
                        })).iterator();
                      case 11:
                        if (!(this._10__yield_zc5nt1_c0a0c0a0e_it.hasNext())) {
                          this.__CP__ = 13;
                          break;
                        }
                        this._10__yield_zc5nt1_c0a0c0a0e = this._10__yield_zc5nt1_c0a0c0a0e_it.next();
                        this.__CP__ = 12;
                        break;
                      case 13:
                        this._14__yield_zc5nt1_d0a0c0a0e_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getChildren(MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4b1L, "pointedBy_a")).iterator().hasNext();
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedContainmentLink(it, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4b1L, "pointedBy_a"));
                          }
                        })).iterator();
                      case 15:
                        if (!(this._14__yield_zc5nt1_d0a0c0a0e_it.hasNext())) {
                          this.__CP__ = 17;
                          break;
                        }
                        this._14__yield_zc5nt1_d0a0c0a0e = this._14__yield_zc5nt1_d0a0c0a0e_it.next();
                        this.__CP__ = 16;
                        break;
                      case 17:
                        this._18__yield_zc5nt1_e0a0c0a0e_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e48dL, "B")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getChildren(MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4c0L, "pointedBy_b")).iterator().hasNext();
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedContainmentLink(it, MetaAdapterFactory.getContainmentLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e48dL, 0x72082dd37174e4c0L, "pointedBy_b"));
                          }
                        })).iterator();
                      case 19:
                        if (!(this._18__yield_zc5nt1_e0a0c0a0e_it.hasNext())) {
                          this.__CP__ = 21;
                          break;
                        }
                        this._18__yield_zc5nt1_e0a0c0a0e = this._18__yield_zc5nt1_e0a0c0a0e_it.next();
                        this.__CP__ = 20;
                        break;
                      case 21:
                        this._22__yield_zc5nt1_f0a0c0a0e_it = Sequence.fromIterable(Sequence.fromIterable(CommandUtil.nodes(CommandUtil.createConsoleScope(null, false, context))).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e492L, "B_Reference"))) || SNodeOperations.isInstanceOf(it, SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x669610ca6c43422eL, 0x9f37c5c3511f4ef8L, "sample.lang2"), 0x72082dd37174e492L, "B_Reference")));
                          }
                        }).where(new IWhereFilter<SNode>() {
                          public boolean accept(SNode it) {
                            return it.getReference(MetaAdapterFactory.getReferenceLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e492L, 0x72082dd37174e493L, "target")) != null;
                          }
                        }).select(new ISelector<SNode, Problem>() {
                          public Problem select(SNode it) {
                            return DeprecatedConceptMemberNotMigratedProblem.deprecatedReferenceLink(it, MetaAdapterFactory.getReferenceLink(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, 0x72082dd37174e492L, 0x72082dd37174e493L, "target"));
                          }
                        })).iterator();
                      case 23:
                        if (!(this._22__yield_zc5nt1_f0a0c0a0e_it.hasNext())) {
                          this.__CP__ = 1;
                          break;
                        }
                        this._22__yield_zc5nt1_f0a0c0a0e = this._22__yield_zc5nt1_f0a0c0a0e_it.next();
                        this.__CP__ = 24;
                        break;
                      case 6:
                        this.__CP__ = 3;
                        this.yield(_2__yield_zc5nt1_a0a0c0a0e);
                        return true;
                      case 10:
                        this.__CP__ = 7;
                        this.yield(_6__yield_zc5nt1_b0a0c0a0e);
                        return true;
                      case 14:
                        this.__CP__ = 11;
                        this.yield(_10__yield_zc5nt1_c0a0c0a0e);
                        return true;
                      case 18:
                        this.__CP__ = 15;
                        this.yield(_14__yield_zc5nt1_d0a0c0a0e);
                        return true;
                      case 22:
                        this.__CP__ = 19;
                        this.yield(_18__yield_zc5nt1_e0a0c0a0e);
                        return true;
                      case 25:
                        this.__CP__ = 23;
                        this.yield(_22__yield_zc5nt1_f0a0c0a0e);
                        return true;
                      case 0:
                        this.__CP__ = 2;
                        break;
                      case 4:
                        this.__CP__ = 6;
                        break;
                      case 8:
                        this.__CP__ = 10;
                        break;
                      case 12:
                        this.__CP__ = 14;
                        break;
                      case 16:
                        this.__CP__ = 18;
                        break;
                      case 20:
                        this.__CP__ = 22;
                        break;
                      case 24:
                        this.__CP__ = 25;
                        break;
                      default:
                        break __loop__;
                    }
                  } while (true);
                  return false;
                }
                private Problem _2__yield_zc5nt1_a0a0c0a0e;
                private Iterator<Problem> _2__yield_zc5nt1_a0a0c0a0e_it;
                private Problem _6__yield_zc5nt1_b0a0c0a0e;
                private Iterator<Problem> _6__yield_zc5nt1_b0a0c0a0e_it;
                private Problem _10__yield_zc5nt1_c0a0c0a0e;
                private Iterator<Problem> _10__yield_zc5nt1_c0a0c0a0e_it;
                private Problem _14__yield_zc5nt1_d0a0c0a0e;
                private Iterator<Problem> _14__yield_zc5nt1_d0a0c0a0e_it;
                private Problem _18__yield_zc5nt1_e0a0c0a0e;
                private Iterator<Problem> _18__yield_zc5nt1_e0a0c0a0e_it;
                private Problem _22__yield_zc5nt1_f0a0c0a0e;
                private Iterator<Problem> _22__yield_zc5nt1_f0a0c0a0e_it;
              };
            }
          };
        }
      });
    }
  }
  public MigrationScriptReference getDescriptor() {
    return new MigrationScriptReference(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 1);
  }
  public static boolean isMovedConcept(SAbstractConcept c) {
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e48dL, "B")))) {
      return true;
    }
    if (SConceptOperations.isExactly(SNodeOperations.asSConcept(c), SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x8216fa52aa014b4dL, 0x94a065b169678b1cL, "sample.lang"), 0x72082dd37174e492L, "B_Reference")))) {
      return true;
    }
    return false;
  }
}
