package common.interfaces;

/*Generated by MPS */

import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.HashSet;

public abstract class AbstractIPointerTarget implements IPointerTarget {

  protected Map<String, Set<IPointer>> pointsToMe = new HashMap<String, Set<IPointer>>();


  @Override
  public void pointsToMe(IPointer inPointer) {
    if (!(canPointToMe(inPointer))) {
      throw new RuntimeException("cannot point to me: " + inPointer);
    }

    if (!(pointsToMe.containsKey(inPointer.target().metaType()))) {
      pointsToMe.put(inPointer.target().metaType(), new HashSet<IPointer>());
    }

    pointsToMe.get(inPointer.target().metaType()).add(inPointer);
  }

}
