package common.interfaces;

/*Generated by MPS */


public interface IPointerTarget {

  String metaType();
  String name();
  void pointsToMe(IPointer inPointer);
  boolean canPointToMe(IPointer inPointer);
}
